/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAccountManagersRouteImport } from './routes/_authenticated/account-managers'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFeaturesRouteImport } from './routes/_authenticated/features'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSubscriptionsRouteImport } from './routes/_authenticated/subscriptions'
import { Route as AuthenticatedTicketsRouteImport } from './routes/_authenticated/tickets'
import { Route as AuthenticatedClientClientIdRouteImport } from './routes/_authenticated/client.$clientId'
import { Route as AuthenticatedFeatureFeatureIdRouteImport } from './routes/_authenticated/feature.$featureId'
import { Route as AuthenticatedTicketTicketIdRouteImport } from './routes/_authenticated/ticket.$ticketId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountManagersRoute =
  AuthenticatedAccountManagersRouteImport.update({
    id: '/account-managers',
    path: '/account-managers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeaturesRoute = AuthenticatedFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubscriptionsRoute =
  AuthenticatedSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTicketsRoute = AuthenticatedTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientClientIdRoute =
  AuthenticatedClientClientIdRouteImport.update({
    id: '/client/$clientId',
    path: '/client/$clientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFeatureFeatureIdRoute =
  AuthenticatedFeatureFeatureIdRouteImport.update({
    id: '/feature/$featureId',
    path: '/feature/$featureId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTicketTicketIdRoute =
  AuthenticatedTicketTicketIdRouteImport.update({
    id: '/ticket/$ticketId',
    path: '/ticket/$ticketId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/account-managers': typeof AuthenticatedAccountManagersRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/features': typeof AuthenticatedFeaturesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/client/$clientId': typeof AuthenticatedClientClientIdRoute
  '/feature/$featureId': typeof AuthenticatedFeatureFeatureIdRoute
  '/ticket/$ticketId': typeof AuthenticatedTicketTicketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/account-managers': typeof AuthenticatedAccountManagersRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/features': typeof AuthenticatedFeaturesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/client/$clientId': typeof AuthenticatedClientClientIdRoute
  '/feature/$featureId': typeof AuthenticatedFeatureFeatureIdRoute
  '/ticket/$ticketId': typeof AuthenticatedTicketTicketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/account-managers': typeof AuthenticatedAccountManagersRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/features': typeof AuthenticatedFeaturesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/_authenticated/tickets': typeof AuthenticatedTicketsRoute
  '/_authenticated/client/$clientId': typeof AuthenticatedClientClientIdRoute
  '/_authenticated/feature/$featureId': typeof AuthenticatedFeatureFeatureIdRoute
  '/_authenticated/ticket/$ticketId': typeof AuthenticatedTicketTicketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/account-managers'
    | '/activity'
    | '/clients'
    | '/dashboard'
    | '/features'
    | '/profile'
    | '/settings'
    | '/subscriptions'
    | '/tickets'
    | '/client/$clientId'
    | '/feature/$featureId'
    | '/ticket/$ticketId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/account-managers'
    | '/activity'
    | '/clients'
    | '/dashboard'
    | '/features'
    | '/profile'
    | '/settings'
    | '/subscriptions'
    | '/tickets'
    | '/client/$clientId'
    | '/feature/$featureId'
    | '/ticket/$ticketId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/account-managers'
    | '/_authenticated/activity'
    | '/_authenticated/clients'
    | '/_authenticated/dashboard'
    | '/_authenticated/features'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/subscriptions'
    | '/_authenticated/tickets'
    | '/_authenticated/client/$clientId'
    | '/_authenticated/feature/$featureId'
    | '/_authenticated/ticket/$ticketId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account-managers': {
      id: '/_authenticated/account-managers'
      path: '/account-managers'
      fullPath: '/account-managers'
      preLoaderRoute: typeof AuthenticatedAccountManagersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/features': {
      id: '/_authenticated/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof AuthenticatedFeaturesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscriptions': {
      id: '/_authenticated/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof AuthenticatedSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tickets': {
      id: '/_authenticated/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthenticatedTicketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/$clientId': {
      id: '/_authenticated/client/$clientId'
      path: '/client/$clientId'
      fullPath: '/client/$clientId'
      preLoaderRoute: typeof AuthenticatedClientClientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feature/$featureId': {
      id: '/_authenticated/feature/$featureId'
      path: '/feature/$featureId'
      fullPath: '/feature/$featureId'
      preLoaderRoute: typeof AuthenticatedFeatureFeatureIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ticket/$ticketId': {
      id: '/_authenticated/ticket/$ticketId'
      path: '/ticket/$ticketId'
      fullPath: '/ticket/$ticketId'
      preLoaderRoute: typeof AuthenticatedTicketTicketIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountManagersRoute: typeof AuthenticatedAccountManagersRoute
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFeaturesRoute: typeof AuthenticatedFeaturesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSubscriptionsRoute: typeof AuthenticatedSubscriptionsRoute
  AuthenticatedTicketsRoute: typeof AuthenticatedTicketsRoute
  AuthenticatedClientClientIdRoute: typeof AuthenticatedClientClientIdRoute
  AuthenticatedFeatureFeatureIdRoute: typeof AuthenticatedFeatureFeatureIdRoute
  AuthenticatedTicketTicketIdRoute: typeof AuthenticatedTicketTicketIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountManagersRoute: AuthenticatedAccountManagersRoute,
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFeaturesRoute: AuthenticatedFeaturesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSubscriptionsRoute: AuthenticatedSubscriptionsRoute,
  AuthenticatedTicketsRoute: AuthenticatedTicketsRoute,
  AuthenticatedClientClientIdRoute: AuthenticatedClientClientIdRoute,
  AuthenticatedFeatureFeatureIdRoute: AuthenticatedFeatureFeatureIdRoute,
  AuthenticatedTicketTicketIdRoute: AuthenticatedTicketTicketIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
